#服务端口
server:
  port: 10086

#应用名称
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        #用户服务模块
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        #支付服务模块
        - id: pay-service
          uri: lb://pay-service
          predicates:
            - Path=/pay/**
        #订单服务模块
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**

    lobalcors:
      add-tp-simple-url-handler-mapping: true #解决options请求被拦截
      cors-configurations:
        '[/**]': # 匹配所有请求
          allowedOrigins: #允许跨域的范围 *代表所有
            - "http://localhost:8090"
            - "http://www.leyou.com"
          allowedMethods: # 允许跨域的方法
            - GET
            - POST
            - PUT
            - DELETE
          alowedHeaders: "*" #允许在请求头中携带的头信息
          allowCredentials: true #是否允许携带cookie
          maxAge: 360000 #跨域有效期

#拦截器排除路径
filter:
  excludePath:
    - /user/login #登录
    - /user/register #注册
