#服务端口
server:
  port: ${utils.server.port[0]}
#应用名称
spring:
  profiles:
    active: utils
  application:
    name: ${utils.server.name[0]}
    #数据库连接
  datasource:
    url: jdbc:mysql://${utils.mysql.url[0]}?userSSL=false&serverTimezone=GMT&allowMultiQueries=true
    driver-class-name: ${utils.mysql.driver}
    username: ${utils.mysql.username[0]}
    password: ${utils.mysql.password[0]}
