#服务端口
server:
  port: ${utils.server.port[2]}
#应用名称
spring:
  profiles:
    active: utils
  application:
    name: ${utils.server.name[2]}
  #数据库连接
  datasource:
    url: jdbc:mysql://${utils.mysql.url[2]}?userSSL=false&serverTimezone=GMT&allowMultiQueries=true
    driver-class-name: ${utils.mysql.driver}
    username: ${utils.mysql.username[2]}
    password: ${utils.mysql.password[2]}
