#服务端口
server:
  port: ${utils.server.port[1]}
#应用名称
spring:
  application:
    name: ${utils.server.name[1]}
  profiles:
    active: utils
  #数据库连接
  datasource:
    url: jdbc:mysql://${utils.mysql.url[1]}?userSSL=false&serverTimezone=GMT&allowMultiQueries=true
    driver-class-name: ${utils.mysql.driver}
    username: ${utils.mysql.username[1]}
    password: ${utils.mysql.password[1]}